 language: node_js
 node_js:
   - "0.10"
 env:
   global:
     secure: |-
        UIWglpU0Wb3EhXyY6bFw8SX/muaKlSogZM1axrLNzpuHafJLixexEgrFy19j2uXnF/IpaIgiEfPiCY/ym9lA/uHYVi19QExm+msxItEiObhD6sUcP9SXZbcucIaC1WBtmz0uCvawz3nwvSvwLoZ+OMnmNWvWWvhl9rekdUG/Lyk=

 before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g bower
  - npm install
  - bower install

 script: gulp && gulp sauce
